# Changed to Mics Credentia
name: CI/CD Pipeline EMP-Typescript

on:
  push:
    branches: [ developement ]
  pull_request:
    branches: [ developement ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
       
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: oriontechmen/env-typescript:dev

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      
    - name: Deploy to Ec2 Instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          sh prune.sh
          sudo chmod 666 /var/run/docker.sock
          cd environmental-mapping-web-backend-001/
          git checkout developement
          git fetch origin developement
           git reset --hard origin/developement
          docker-compose -f docker-compose.dev.yml stop
          docker-compose -f docker-compose.dev.yml rm -f
          docker-compose -f docker-compose.dev.yml pull   
          docker-compose -f docker-compose.dev.yml up -d